### ISSUE TITLE
Example use of C2BSimulate and C2BRegister

### ISSUE THREAD

**Issue by titleistfour** [Kabangi/mpesa#1]
Hello,

Could you please provide an example call for C2BRegister and C2BSimulate in Laravel?  It is not entirely intuitive how I should be calling those.

Thank you

**Comment by Kabangi** [comment]
Hi @titleistfour  
Sorry for not having this explicit but unfortunately this might not happen. Am in the process of retiring support for laravel and instead have a separate repo implementing this package. Shooting to have this up by weekend. Will update here with the link and close the issue then.

**Comment by Kabangi** [comment]
I have separated laravel implementation to https://packagist.org/packages/kabangi/mpesa-laravel

Will improve the docs later this week
