### ISSUE TITLE
Warning: curl_setopt(): supplied resource is not a valid cURL handle resource in /Users/lily/mpesa/vendor/kabangi/mpesa/src/Mpesa/Engine/CurlRequest.php on line 15

### ISSUE THREAD

**Issue by danielin** [Kabangi/mpesa#4]
This is the test code:
`<?php
require "vendor/autoload.php";

use Kabangi\Mpesa\Native\Mpesa;

$mpesa = new Mpesa();

$response = $mpesa->STKPush([
    'amount' => 10,
    'PartyA' => '254713963186',
    'PhoneNumber' => '254713963186',
    'CallBackURL' => 'https://example.com/v1/payments/C2B/confirmation',
    'AccountReference' => 'test',
    'TransactionDesc' => 'Test'
]);
header('Content-Type: application/json');
echo json_encode($response);`

This is the whole error page:

`

( ! ) Warning: curl_setopt(): supplied resource is not a valid cURL handle resource in /Users/lily/mpesa/vendor/kabangi/mpesa/src/Mpesa/Engine/CurlRequest.php on line 15
--

1 | 0.0178 | 400832 | {main}( ) | .../test.php:0
2 | 0.1002 | 1134120 | Kabangi\Mpesa\Native\Mpesa->STKPush( ) | .../test.php:9
3 | 0.1079 | 1195984 | Kabangi\Mpesa\LipaNaMpesaOnline\STKPush->submit( ) | .../MpesaTrait.php:18
4 | 0.1154 | 1199848 | Kabangi\Mpesa\Engine\Core->makePostRequest( ) | .../STKPush.php:75
5 | 0.9990 | 1199792 | Kabangi\Mpesa\Engine\Core->request( ) | .../Core.php:151
6 | 1.0114 | 1227976 | Kabangi\Mpesa\Engine\CurlRequest->setOption( ) | .../Core.php:164
7 | 1.0114 | 1227976 | curl_setopt ( ) | .../CurlRequest.php:15

`

**Comment by Kabangi** [comment]
Fixed on the latest version. 

Thanks for reporting

**Comment by danielin** [comment]
Hi Julius,
May I know which company are you working for now?

Daniel

**Comment by Kabangi** [comment]
Working for “ConnectHealth, Inc.” why if you do not mind?

**Comment by danielin** [comment]
Just being curious, I admired your skills.
Maybe we can work out something together.

BTW, as a info exchange, I work for Tecno now.
