### ISSUE TITLE
Invalid params to C2BSimulate

### ISSUE THREAD

**Issue by ngugijames** [Kabangi/mpesa#7]
https://github.com/ConnectHealthInc/mpesa/blob/e480db3dae0c78939d4ce9f2d3153514cb135847/src/Mpesa/Engine/MpesaTrait.php#L33

I am certain this should be ` return $simulate->submit($params,$appName); `
This has taken alot of debugging time.

**Comment by Alecckie** [comment]
@ngugijames ... You are right. I changed that line of code and now C2B works just fine
[public function C2BSimulate($params = [],$appName='default'){
        $simulate = new Simulate($this->engine);
        return $simulate->submit($params,$appName);
    }](url)
